name: 'Setup Node and install deps'
description: 'Install Node.js 20 and project dependencies'
inputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Cache ESLint cache
      uses: actions/cache@v4
      with:
        path: .cache/eslint
        key: eslint-${{ runner.os }}-${{ hashFiles('package-lock.json', '.eslintrc*', 'eslint.config.*') }}
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: node-modules-${{ runner.os }}-
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      env:
        npm_config_platform: linux
        npm_config_arch: x64
        SHARP_IGNORE_GLOBAL_LIBVIPS: '1'
      run: npm ci --include=optional
