// AUTO-GENERATED by scripts/generate-build-info.ts

export type NodeEnv = 'development' | 'test' | 'production';
export interface BuildInfo {
  commit: string;
  shortCommit: string;
  branch: string;
  prNumber: string | null;
  env: NodeEnv;
  url: string;
  runtime: string;
  buildIso: string;
  buildYear: string;
  isProd: boolean;
}

export const buildInfo: BuildInfo = {
  "commit": "e474c98d84f06a17f391252e7a972310f5dd78f1",
  "shortCommit": "e474c98",
  "branch": "work",
  "prNumber": null,
  "env": "development",
  "url": "http://localhost:3000",
  "runtime": "node v22.18.0",
  "buildIso": "2025-08-30T17:53:20.715Z",
  "buildYear": "2025",
  "isProd": false
} as const;
