// AUTO-GENERATED by scripts/generate-build-info.ts

export type NodeEnv = 'development' | 'test' | 'production';
export interface BuildInfo {
  commit: string;
  shortCommit: string;
  branch: string;
  prNumber: string | null;
  ciRunId: string | null;
  env: NodeEnv;
  url: string;
  runtime: string;
  buildIso: string;
  buildYear: string;
  isProd: boolean;
}

export const buildInfo: BuildInfo = {
  "commit": "2ca252782a3d661053698b66bdd73f20134be3b1",
  "shortCommit": "2ca2527",
  "branch": "cipher/refactor-shaolin-scrolls-release-list",
  "prNumber": null,
  "ciRunId": null,
  "env": "development",
  "url": "http://localhost:3000",
  "runtime": "node v22.18.0",
  "buildIso": "2025-09-03T05:52:25.094Z",
  "buildYear": "2025",
  "isProd": false
} as const;
