// AUTO-GENERATED by scripts/generate-build-info.ts

export type NodeEnv = 'development' | 'test' | 'production';
export interface BuildInfo {
  commit: string;
  shortCommit: string;
  branch: string;
  prNumber: string | null;
  ciRunId: string | null;
  env: NodeEnv;
  url: string;
  runtime: string;
  buildIso: string;
  buildYear: string;
  isProd: boolean;
}

export const buildInfo: BuildInfo = {
  "commit": "3b1d4d0bb1f3a5682a07941cd438919bb82a7857",
  "shortCommit": "3b1d4d0",
  "branch": "giannis/fix-deprecated-property",
  "prNumber": null,
  "ciRunId": null,
  "env": "development",
  "url": "http://localhost:3000",
  "runtime": "node v22.18.0",
  "buildIso": "2025-08-31T23:56:22.504Z",
  "buildYear": "2025",
  "isProd": false
} as const;
