name: e2e

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # To skip browser installs entirely, uncomment the following lines to use
    # Playwright's prebuilt container image.
    # container:
    #   image: mcr.microsoft.com/playwright:v1.55.0-noble
    env:
      NODE_ENV: test
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
      PLAYWRIGHT_USE_SYSTEM_CHROME: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(npx @playwright/test --version | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright system dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true' && env.PLAYWRIGHT_USE_SYSTEM_CHROME != '1'
        run: npx playwright install-deps chromium

      - name: Install Playwright Chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true' && env.PLAYWRIGHT_USE_SYSTEM_CHROME != '1'
        run: npx playwright install chromium

      - name: Install system Chromium (fallback)
        if: env.PLAYWRIGHT_USE_SYSTEM_CHROME == '1'
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium

      - name: Run e2e tests
        run: npx playwright test --reporter=html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip
