name: Lockfile Sync Check
on:
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
jobs:
  lockfile-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure lockfile updated when package.json changes
        run: |
          CHANGED_FILES="$(git diff --name-only HEAD^ HEAD || true)"
          if echo "$CHANGED_FILES" | grep -qx "package.json" && \
             ! echo "$CHANGED_FILES" | grep -qx "package-lock.json"; then
            echo "::error ::package.json changed but package-lock.json did not. Run 'npm install' and commit the lockfile."
            exit 1
          fi

